fix: removes `Readable.fromWeb` and `Readable.toWeb` methods
nodejs/readable-stream pull request #506
Opened 2023-02-26 17:11 UTC by RishabhKodes

fixes: https://github.com/nodejs/readable-stream/issues/482

The `Readable.fromWeb` and `Readable.toWeb` methods were no longer being used from here (instead being imported from `require(stream')` method).

This pr removes both methods during the build when the module is extracted from Node.js.

2023-02-26 17:55 UTC, mcollina commented
Can you move those to the replacements.mjs file?

2023-02-26 18:39 UTC, RishabhKodes commented
> Can you move those to the replacements.mjs file?

You mean the whole 

> Can you move those to the replacements.mjs file?

Do you mean moving the code changes I made, or the doing something like this https://github.com/nodejs/readable-stream/blob/main/build/build.mjs#L94 ?

2023-02-27 08:40 UTC, mcollina commented
Using the regular expressions instead.

2023-02-27 11:34 UTC, RishabhKodes commented
@mcollina I've moved the changes to `replacements.mjs` and put the code inside a function and then imported it in the `build.mjs` file, PTAL let me know if that's fine.

2023-02-27 12:33 UTC, mcollina requested changes
What I was trying to say is to use the system that's already in place and not add new code, just replacements via regexps.

2023-02-28 08:54 UTC, mcollina approved these changes
lgtm

2023-02-28 16:22 UTC, benjamingr approved these changes

2023-03-02 14:59 UTC, RishabhKodes commented
@benjamingr @mcollina the `Node.js / Node.js (windows-latest, 18.x)` test is still failing after the re-run.

2023-03-14 08:14 UTC, RishabhKodes commented
@mcollina @benjamingr, an update on this pr? Has been idle for a long time.

2023-05-08 09:40 UTC, merged

2023-05-08 09:41 UTC, mcollina commented
Sorry about it, it was buried down my github notifications.